import { useState } from 'react';
import { Card, SectionTitle } from '../ui/Card';
import { Field, TextInput } from '../ui/Field';
import { splitTags } from '../../lib/hologramApi';
import type { IdentityMedia, IdentityPayload } from '../../lib/hologramApi';

const empty: IdentityPayload = { id: '', title: '', index: 0, enabled: true, default: false, keywords: [] };

export function IdentityCatalog({ items, onCreate, onUpdate, onDelete, onTest }: { items: IdentityMedia[]; onCreate: (payload: IdentityPayload) => Promise<boolean>; onUpdate: (id: string, payload: IdentityPayload) => Promise<boolean>; onDelete: (id: string) => Promise<boolean>; onTest: (id: string) => Promise<boolean> }) {
  const [editing, setEditing] = useState<IdentityPayload | null>(null);
  const [keywords, setKeywords] = useState('');
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!editing?.id.trim() || !editing.title.trim() || editing.index < 0 || editing.index > 255) return; const payload = { ...editing, id: editing.id.trim(), title: editing.title.trim(), keywords: splitTags(keywords) }; const ok = items.some((item) => item.id === editing.id) ? await onUpdate(editing.id, payload) : await onCreate(payload); if (ok) setEditing(null); };
  return <Card><div className="flex items-center justify-between"><SectionTitle>Identidades</SectionTitle><button type="button" onClick={() => { setEditing(empty); setKeywords(''); }} className="rounded-xl bg-[#E25C1D] px-3 py-2 text-xs font-bold text-white">Nueva identidad</button></div><p className="text-xs text-gray-500">Holomind es el fallback y no puede eliminarse.</p><div className="space-y-2">{items.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-gray-200 p-3 dark:border-slate-700"><div><p className="font-bold">{item.title} <span className="text-xs font-normal text-gray-500">({item.id})</span></p><p className="text-xs text-gray-500">Índice {item.index} · {item.keywords.join(', ') || 'sin keywords'}{item.default ? ' · Predeterminada' : ''}</p></div><div className="flex gap-2"><button type="button" onClick={() => void onTest(item.id)} className="rounded-lg border px-2 py-1 text-xs">Probar</button><button type="button" onClick={() => { setEditing({ ...item }); setKeywords(item.keywords.join(', ')); }} className="rounded-lg border px-2 py-1 text-xs">Editar</button><button type="button" disabled={item.default || item.id === 'holomind'} onClick={() => { if (window.confirm(`¿Eliminar ${item.title}?`)) void onDelete(item.id); }} className="rounded-lg border px-2 py-1 text-xs text-red-600 disabled:opacity-40">Eliminar</button></div></div>)}</div>{editing && <form onSubmit={(event) => void submit(event)} className="grid gap-3 rounded-2xl border border-[#E25C1D]/30 p-4 sm:grid-cols-2"><Field label="ID"><TextInput required value={editing.id} onChange={(e) => setEditing({ ...editing, id: e.target.value })} /></Field><Field label="Título"><TextInput required value={editing.title} onChange={(e) => setEditing({ ...editing, title: e.target.value })} /></Field><Field label="Índice 0–255"><TextInput required type="number" min={0} max={255} value={editing.index} onChange={(e) => setEditing({ ...editing, index: Number(e.target.value) })} /></Field><Field label="Keywords separadas por coma"><TextInput value={keywords} onChange={(e) => setKeywords(e.target.value)} /></Field><label className="flex gap-2 text-xs font-semibold"><input type="checkbox" checked={editing.enabled} onChange={(e) => setEditing({ ...editing, enabled: e.target.checked })} /> Habilitada</label><label className="flex gap-2 text-xs font-semibold"><input type="checkbox" checked={editing.default} onChange={(e) => setEditing({ ...editing, default: e.target.checked })} /> Predeterminada</label><div className="flex gap-2 sm:col-span-2"><button className="rounded-xl bg-[#E25C1D] px-4 py-2 text-xs font-bold text-white">Guardar</button><button type="button" onClick={() => setEditing(null)} className="rounded-xl border px-4 py-2 text-xs font-bold">Cancelar</button></div></form>}</Card>;
}
